/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as CarsRouteRouteImport } from './routes/cars/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCarsRouteRouteImport } from './routes/admin/cars/route'
import { Route as AuctionsIndexRouteImport } from './routes/auctions/index'
import { Route as AuctionsAuctionIdRouteImport } from './routes/auctions/$auctionId'
import { Route as BusinessSelectRouteImport } from './routes/business/select'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as CarsCarIdRouteImport } from './routes/cars/$carId'
import { Route as DealersIndexRouteImport } from './routes/dealers/index'
import { Route as DealersDealerIdRouteImport } from './routes/dealers/$dealerId'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as InspectionsIndexRouteImport } from './routes/inspections/index'
import { Route as InspectionsInspectionIdRouteImport } from './routes/inspections/$inspectionId'
import { Route as AdminAdsIndexRouteImport } from './routes/admin/ads/index'
import { Route as AdminAuctionsIndexRouteImport } from './routes/admin/auctions/index'
import { Route as AdminCarsNewRouteImport } from './routes/admin/cars/new'
import { Route as AdminDealersIndexRouteImport } from './routes/admin/dealers/index'
import { Route as AdminFinanceIndexRouteImport } from './routes/admin/finance/index'
import { Route as AdminInspectionsIndexRouteImport } from './routes/admin/inspections/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRouteRoute = CarsRouteRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCarsRouteRoute = AdminCarsRouteRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionIdRoute = AuctionsAuctionIdRouteImport.update({
  id: '/auctions/$auctionId',
  path: '/auctions/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSelectRoute = BusinessSelectRouteImport.update({
  id: '/business/select',
  path: '/business/select',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarsRouteRoute,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => CarsRouteRoute,
} as any)
const DealersIndexRoute = DealersIndexRouteImport.update({
  id: '/dealers/',
  path: '/dealers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersDealerIdRoute = DealersDealerIdRouteImport.update({
  id: '/dealers/$dealerId',
  path: '/dealers/$dealerId',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIndexRoute = InspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsInspectionIdRoute = InspectionsInspectionIdRouteImport.update({
  id: '/inspections/$inspectionId',
  path: '/inspections/$inspectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsIndexRoute = AdminAdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuctionsIndexRoute = AdminAuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCarsNewRoute = AdminCarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCarsRouteRoute,
} as any)
const AdminDealersIndexRoute = AdminDealersIndexRouteImport.update({
  id: '/dealers/',
  path: '/dealers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceIndexRoute = AdminFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInspectionsIndexRoute = AdminInspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cars': typeof CarsRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin/cars': typeof AdminCarsRouteRouteWithChildren
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/business/select': typeof BusinessSelectRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/dealers/': typeof DealersIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/admin/cars/new': typeof AdminCarsNewRoute
  '/admin/ads/': typeof AdminAdsIndexRoute
  '/admin/auctions/': typeof AdminAuctionsIndexRoute
  '/admin/dealers/': typeof AdminDealersIndexRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/inspections/': typeof AdminInspectionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin/cars': typeof AdminCarsRouteRouteWithChildren
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/business/select': typeof BusinessSelectRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdRoute
  '/admin': typeof AdminIndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/cars': typeof CarsIndexRoute
  '/dealers': typeof DealersIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/inspections': typeof InspectionsIndexRoute
  '/admin/cars/new': typeof AdminCarsNewRoute
  '/admin/ads': typeof AdminAdsIndexRoute
  '/admin/auctions': typeof AdminAuctionsIndexRoute
  '/admin/dealers': typeof AdminDealersIndexRoute
  '/admin/finance': typeof AdminFinanceIndexRoute
  '/admin/inspections': typeof AdminInspectionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cars': typeof CarsRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin/cars': typeof AdminCarsRouteRouteWithChildren
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/business/select': typeof BusinessSelectRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/dealers/': typeof DealersIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/admin/cars/new': typeof AdminCarsNewRoute
  '/admin/ads/': typeof AdminAdsIndexRoute
  '/admin/auctions/': typeof AdminAuctionsIndexRoute
  '/admin/dealers/': typeof AdminDealersIndexRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/inspections/': typeof AdminInspectionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cars'
    | '/admin-login'
    | '/login'
    | '/register'
    | '/verify'
    | '/admin/cars'
    | '/auctions/$auctionId'
    | '/business/select'
    | '/cars/$carId'
    | '/dealers/$dealerId'
    | '/inspections/$inspectionId'
    | '/admin/'
    | '/auctions/'
    | '/cars/'
    | '/dealers/'
    | '/finance/'
    | '/inspections/'
    | '/admin/cars/new'
    | '/admin/ads/'
    | '/admin/auctions/'
    | '/admin/dealers/'
    | '/admin/finance/'
    | '/admin/inspections/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/login'
    | '/register'
    | '/verify'
    | '/admin/cars'
    | '/auctions/$auctionId'
    | '/business/select'
    | '/cars/$carId'
    | '/dealers/$dealerId'
    | '/inspections/$inspectionId'
    | '/admin'
    | '/auctions'
    | '/cars'
    | '/dealers'
    | '/finance'
    | '/inspections'
    | '/admin/cars/new'
    | '/admin/ads'
    | '/admin/auctions'
    | '/admin/dealers'
    | '/admin/finance'
    | '/admin/inspections'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cars'
    | '/admin-login'
    | '/login'
    | '/register'
    | '/verify'
    | '/admin/cars'
    | '/auctions/$auctionId'
    | '/business/select'
    | '/cars/$carId'
    | '/dealers/$dealerId'
    | '/inspections/$inspectionId'
    | '/admin/'
    | '/auctions/'
    | '/cars/'
    | '/dealers/'
    | '/finance/'
    | '/inspections/'
    | '/admin/cars/new'
    | '/admin/ads/'
    | '/admin/auctions/'
    | '/admin/dealers/'
    | '/admin/finance/'
    | '/admin/inspections/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CarsRouteRoute: typeof CarsRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
  AuctionsAuctionIdRoute: typeof AuctionsAuctionIdRoute
  BusinessSelectRoute: typeof BusinessSelectRoute
  DealersDealerIdRoute: typeof DealersDealerIdRoute
  InspectionsInspectionIdRoute: typeof InspectionsInspectionIdRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  DealersIndexRoute: typeof DealersIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  InspectionsIndexRoute: typeof InspectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cars': {
      id: '/admin/cars'
      path: '/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminCarsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionId': {
      id: '/auctions/$auctionId'
      path: '/auctions/$auctionId'
      fullPath: '/auctions/$auctionId'
      preLoaderRoute: typeof AuctionsAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/select': {
      id: '/business/select'
      path: '/business/select'
      fullPath: '/business/select'
      preLoaderRoute: typeof BusinessSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof CarsRouteRoute
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof CarsRouteRoute
    }
    '/dealers/': {
      id: '/dealers/'
      path: '/dealers'
      fullPath: '/dealers/'
      preLoaderRoute: typeof DealersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers/$dealerId': {
      id: '/dealers/$dealerId'
      path: '/dealers/$dealerId'
      fullPath: '/dealers/$dealerId'
      preLoaderRoute: typeof DealersDealerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/': {
      id: '/inspections/'
      path: '/inspections'
      fullPath: '/inspections/'
      preLoaderRoute: typeof InspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/$inspectionId': {
      id: '/inspections/$inspectionId'
      path: '/inspections/$inspectionId'
      fullPath: '/inspections/$inspectionId'
      preLoaderRoute: typeof InspectionsInspectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads/': {
      id: '/admin/ads/'
      path: '/ads'
      fullPath: '/admin/ads/'
      preLoaderRoute: typeof AdminAdsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auctions/': {
      id: '/admin/auctions/'
      path: '/auctions'
      fullPath: '/admin/auctions/'
      preLoaderRoute: typeof AdminAuctionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cars/new': {
      id: '/admin/cars/new'
      path: '/new'
      fullPath: '/admin/cars/new'
      preLoaderRoute: typeof AdminCarsNewRouteImport
      parentRoute: typeof AdminCarsRouteRoute
    }
    '/admin/dealers/': {
      id: '/admin/dealers/'
      path: '/dealers'
      fullPath: '/admin/dealers/'
      preLoaderRoute: typeof AdminDealersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finance/': {
      id: '/admin/finance/'
      path: '/finance'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AdminFinanceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inspections/': {
      id: '/admin/inspections/'
      path: '/inspections'
      fullPath: '/admin/inspections/'
      preLoaderRoute: typeof AdminInspectionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminCarsRouteRouteChildren {
  AdminCarsNewRoute: typeof AdminCarsNewRoute
}

const AdminCarsRouteRouteChildren: AdminCarsRouteRouteChildren = {
  AdminCarsNewRoute: AdminCarsNewRoute,
}

const AdminCarsRouteRouteWithChildren = AdminCarsRouteRoute._addFileChildren(
  AdminCarsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCarsRouteRoute: typeof AdminCarsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdsIndexRoute: typeof AdminAdsIndexRoute
  AdminAuctionsIndexRoute: typeof AdminAuctionsIndexRoute
  AdminDealersIndexRoute: typeof AdminDealersIndexRoute
  AdminFinanceIndexRoute: typeof AdminFinanceIndexRoute
  AdminInspectionsIndexRoute: typeof AdminInspectionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCarsRouteRoute: AdminCarsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdsIndexRoute: AdminAdsIndexRoute,
  AdminAuctionsIndexRoute: AdminAuctionsIndexRoute,
  AdminDealersIndexRoute: AdminDealersIndexRoute,
  AdminFinanceIndexRoute: AdminFinanceIndexRoute,
  AdminInspectionsIndexRoute: AdminInspectionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CarsRouteRouteChildren {
  CarsCarIdRoute: typeof CarsCarIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

const CarsRouteRouteChildren: CarsRouteRouteChildren = {
  CarsCarIdRoute: CarsCarIdRoute,
  CarsIndexRoute: CarsIndexRoute,
}

const CarsRouteRouteWithChildren = CarsRouteRoute._addFileChildren(
  CarsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CarsRouteRoute: CarsRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
  AuctionsAuctionIdRoute: AuctionsAuctionIdRoute,
  BusinessSelectRoute: BusinessSelectRoute,
  DealersDealerIdRoute: DealersDealerIdRoute,
  InspectionsInspectionIdRoute: InspectionsInspectionIdRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  DealersIndexRoute: DealersIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  InspectionsIndexRoute: InspectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
